# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oceanEddyRecognition.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 541))
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_file = QtWidgets.QWidget()
        self.tab_file.setObjectName("tab_file")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_file)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 359, 217))
        self.groupBox_3.setObjectName("groupBox_3")
        self.open_file = QtWidgets.QPushButton(self.groupBox_3)
        self.open_file.setGeometry(QtCore.QRect(100, 50, 151, 51))
        self.open_file.setIconSize(QtCore.QSize(16, 16))
        self.open_file.setObjectName("open_file")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_file)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 233, 359, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_info = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_info.setGeometry(QtCore.QRect(10, 40, 341, 151))
        self.textEdit_info.setObjectName("textEdit_info")
        self.groupBox = QtWidgets.QGroupBox(self.tab_file)
        self.groupBox.setGeometry(QtCore.QRect(430, 10, 349, 481))
        self.groupBox.setObjectName("groupBox")
        self.image_preshow = QtWidgets.QLabel(self.groupBox)
        self.image_preshow.setGeometry(QtCore.QRect(10, 20, 121, 41))
        self.image_preshow.setObjectName("image_preshow")
        self.label_show = QtWidgets.QLabel(self.groupBox)
        self.label_show.setGeometry(QtCore.QRect(10, 110, 321, 280))
        self.label_show.setMinimumSize(QtCore.QSize(280, 280))
        self.label_show.setText("")
        self.label_show.setScaledContents(True)
        self.label_show.setObjectName("label_show")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(150, 30, 171, 22))
        self.comboBox.setObjectName("comboBox")
        self.tabWidget.addTab(self.tab_file, "")
        self.tab_process = QtWidgets.QWidget()
        self.tab_process.setObjectName("tab_process")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_process)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 301, 481))
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setGeometry(QtCore.QRect(40, 60, 101, 51))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 140, 101, 51))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_3.setGeometry(QtCore.QRect(40, 220, 101, 51))
        self.checkBox_3.setObjectName("checkBox_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_process)
        self.groupBox_5.setGeometry(QtCore.QRect(430, 10, 331, 481))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 291, 151))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(20, 220, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 141, 111))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(180, 240, 141, 111))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(20, 360, 141, 111))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(180, 360, 141, 111))
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.tab_process)
        self.pushButton.setGeometry(QtCore.QRect(320, 200, 101, 51))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_process, "")
        self.tab_extract = QtWidgets.QWidget()
        self.tab_extract.setObjectName("tab_extract")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_extract)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 301, 481))
        self.groupBox_6.setObjectName("groupBox_6")
        self.checkBox_FD = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_FD.setGeometry(QtCore.QRect(40, 270, 111, 16))
        self.checkBox_FD.setObjectName("checkBox_FD")
        self.checkBox_Harris = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_Harris.setGeometry(QtCore.QRect(40, 78, 111, 16))
        self.checkBox_Harris.setObjectName("checkBox_Harris")
        self.checkBox_GLCM = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_GLCM.setGeometry(QtCore.QRect(40, 174, 111, 16))
        self.checkBox_GLCM.setObjectName("checkBox_GLCM")
        self.extract = QtWidgets.QPushButton(self.tab_extract)
        self.extract.setGeometry(QtCore.QRect(320, 200, 101, 51))
        self.extract.setObjectName("extract")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_extract)
        self.groupBox_7.setGeometry(QtCore.QRect(430, 10, 331, 481))
        self.groupBox_7.setObjectName("groupBox_7")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 291, 221))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_extract, "")
        self.tab_recognize = QtWidgets.QWidget()
        self.tab_recognize.setObjectName("tab_recognize")
        self.tabWidget.addTab(self.tab_recognize, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "选择文件夹"))
        self.open_file.setText(_translate("MainWindow", "浏览文件"))
        self.groupBox_2.setTitle(_translate("MainWindow", "信息显示"))
        self.textEdit_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">选择文件夹名称：</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "预览"))
        self.image_preshow.setText(_translate("MainWindow", "选择预览的图片："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_file), _translate("MainWindow", "1.打开文件"))
        self.groupBox_4.setTitle(_translate("MainWindow", "数据增强"))
        self.checkBox.setText(_translate("MainWindow", "随机裁剪"))
        self.checkBox_2.setText(_translate("MainWindow", "尺度变换"))
        self.checkBox_3.setText(_translate("MainWindow", "旋转变换"))
        self.groupBox_5.setTitle(_translate("MainWindow", "预览"))
        self.label_2.setText(_translate("MainWindow", "原图："))
        self.label_3.setText(_translate("MainWindow", "原图"))
        self.label_4.setText(_translate("MainWindow", "效果图："))
        self.label_5.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "3"))
        self.label_8.setText(_translate("MainWindow", "4"))
        self.pushButton.setText(_translate("MainWindow", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_process), _translate("MainWindow", "2.预处理"))
        self.groupBox_6.setTitle(_translate("MainWindow", "特征选择"))
        self.checkBox_FD.setText(_translate("MainWindow", "FD形状特征"))
        self.checkBox_Harris.setText(_translate("MainWindow", "Harris角点特征"))
        self.checkBox_GLCM.setText(_translate("MainWindow", "GLCM纹理特征"))
        self.extract.setText(_translate("MainWindow", "提取特征"))
        self.groupBox_7.setTitle(_translate("MainWindow", "特征信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_extract), _translate("MainWindow", "3.特征提取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_recognize), _translate("MainWindow", "4.训练与识别"))
